name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  pull_request:
    types: [labeled]

jobs:
  lint:
    if: github.event_name != 'pull_request' || github.event.label.name == 'full-ci'
    uses: ./.github/workflows/lint.yaml

  naming:
    if: github.event_name != 'pull_request' || github.event.label.name == 'full-ci'
    uses: ./.github/workflows/naming.yaml

  pr-size:
    if: github.event_name != 'pull_request' || github.event.label.name == 'full-ci'
    uses: ./.github/workflows/pr-size.yaml

  unit:
    if: github.event_name != 'pull_request' || github.event.label.name == 'full-ci'
    needs: lint
    uses: ./.github/workflows/unit.yaml
