name: repo-yaml

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2

      - run: pip install --no-cache-dir yamllint==1.35.1
      - run: yamllint -s .github deploy
